apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: manas2808/auth
      context: auth
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manas2808/client
      context: client
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: manas2808/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manas2808/orders
      context: orders
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manas2808/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manas2808/payments
      context: payments
      docker:
        dockerfile: Dockerfile      
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .